[plugin]
repository = "https://github.com/Noevain/VoiceDirector.git"
commit = "307aa6c14dbd96515cdca3515f1287746133783f"
owners = ["Noevain"]
project_path = "VoiceDirector"
changelog = "API13 updated,yipee"